explore_node:
  ros__parameters:
    use_sim_time: true
    robot_base_frame: "base_footprint"
    # costmap_topic: "/global_costmap/costmap"
    # costmap_updates_topic: "/global_costmap/costmap_updates"
    costmap_topic: "/map"
    costmap_updates_topic: "/map/map_updates"
    visualize: true
    planner_frequency: 0.33
    progress_timeout: 60.0
    return_to_init: false
    min_frontier_size: 0.15     
    potential_scale: 2.0        
    orientation_scale: 3.0 
    gain_scale: 1.5             
    transform_tolerance: 0.5     
