explore_node:
  ros__parameters:
    use_sim_time: true
    robot_base_frame: "base_footprint"
    costmap_topic: "/map"
    costmap_updates_topic: "/map_updates"
    visualize: true
    planner_frequency: 0.33
    progress_timeout: 60.0
    return_to_init: false
    # -- Tuning per spazi stretti --
    min_frontier_size: 0.70      # Abbassato per entrare in porte e fessure
    potential_scale: 3.0         # Alta priorità alle frontiere vicine
    orientation_scale: 0.0 
    gain_scale: 1.5              # Alta priorità alle zone che scoprono molta mappa
    transform_tolerance: 0.5     # Evita crash se il TF ha un leggero lag nelle rotazioni
    
# alessandrogaggioli@alessandrogaggioli-HP-Laptop-15s-eq3xxx:~/tiago_ws$ ros2 param list /explore_node
#   costmap_topic
#   costmap_updates_topic
#   gain_scale
#   min_frontier_size
#   orientation_scale
#   planner_frequency
#   potential_scale
#   progress_timeout
#   qos_overrides./clock.subscription.depth
#   qos_overrides./clock.subscription.durability
#   qos_overrides./clock.subscription.history
#   qos_overrides./clock.subscription.reliability
#   qos_overrides./parameter_events.publisher.depth
#   qos_overrides./parameter_events.publisher.durability
#   qos_overrides./parameter_events.publisher.history
#   qos_overrides./parameter_events.publisher.reliability
#   return_to_init
#   robot_base_frame
#   transform_tolerance
#   use_sim_time
#   visualize
